// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteLuizaLabs.Aplicacao.Repositorio.Contexto;

namespace TesteLuizaLabs.Aplicacao.Repositorio.Migrations
{
    [DbContext(typeof(EntityFrameworkContext))]
    [Migration("20210513131525_Primeiro")]
    partial class Primeiro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("TesteLuizaLabs.Aplicacao.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
